apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-svc
  labels:
    app: feed-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-svc
  template:
    metadata:
      labels:
        app: feed-svc
    spec:
      containers:
      - name: feed-svc
        image: sachinudacity/udagram-microservices-feed
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi        